Bootstrap: shub
From: singularityhub/ubuntu:latest

%help
echo "Usage: singularity run "


%runscript
# squelch perl complaining about locale settings it doesn't understand
LANG=C
LANGUAGE=$LANG
LC_ALL=$LANG
export LANG LANGUAGE LC_ALL

exec /julia-9d11f62bcb/bin/julia "$@"

%post
apt-get update
apt-get install -y build-essential
apt-get install -y unzip
apt install -y   tar wget  liblzma-dev libz-dev libbz2-dev  libdb-dev gcc g++ zip  gfortran make  
wget https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.4-linux-x86_64.tar.gz
tar -xzf julia-0.6.4-linux-x86_64.tar.gz
cp /julia-9d11f62bcb/bin/julia /usr/bin

# these are specific to scc
# create the directories in case OverlayFS support wasn't built in
for d in /scratch /share /project /projectnb /restricted /usr1 /usr2 /usr3 /usr4 /var/spool/sge;
do
  rm -rf $d
  mkdir $d
done
